# Port
server.port=${PORT:8080}

# Database info
spring.datasource.url=jdbc:postgresql://ep-snowy-dew-atm4lelt-pooler.c-9.us-east-1.aws.neon.tech/Portafolio?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_I8qEtXyWS7rx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Image Route
file.upload-dir=uploads


# Env variables
front.url=${FRONT_URL}
